/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The main NAPI class exposed to Node.js.
 *
 * Usage from JS/TS:
 * ```js
 * const engine = new NativeEngine({ retry: { maxRetries: 3 }, limits: { timeoutMs: 30000 } });
 * engine.registerTool({ name: "lookup", description: "...", inputSchema: {} }, async (args) => { ... });
 * const result = await engine.execute("order = tool('lookup', order_id='123')
order", {});
 * ```
 */
export declare class NativeEngine {
  constructor(config?: NapiConfig | undefined | null)
  /**
   * Register a tool with its definition and JS callback function.
   *
   * The callback receives a JSON value (the tool arguments) and must return
   * a Promise that resolves to a JSON value (the tool result).
   */
  registerTool(definition: NapiToolDefinition, run: (args: any) => Promise<any>): void
  /**
   * Execute a Python script with access to all registered tools.
   *
   * When the script calls `tool('name', ...)`, the corresponding JS callback is invoked.
   * Only the final expression value is returned.
   */
  execute(code: string, inputs?: any | undefined | null): Promise<NapiExecutionResult>
  /** Search registered tools by keyword query. */
  search(query: string, topK?: number | undefined | null): Array<NapiSearchResult>
  /** Get a formatted catalog of all registered tools (for LLM descriptions). */
  getToolCatalog(): string
  /** Get compact tool signatures: `name(param1, param2) -> {field1, field2}`. */
  getToolSignatures(): string
  /** Get the recommended system prompt for LLM conversations. */
  getSystemPrompt(): string
  /** Get the canonical "execute" tool description for LLM adapters. */
  getExecuteToolDescription(): string
  /** Get the canonical "search" tool description for LLM adapters. */
  getSearchToolDescription(): string
  /** Get the canonical JSON Schema for the execute tool's input parameters. */
  getExecuteToolInputSchema(): any
  /** Get the canonical JSON Schema for the search tool's input parameters. */
  getSearchToolInputSchema(): any
  /** Get the number of registered tools. */
  toolCount(): number
  /** Get all trace entries recorded so far. */
  getTraces(): Array<NapiTraceEntry>
  /** Clear all trace entries. */
  clearTraces(): void
}

/** Configuration for the NativeEngine, passed from JS. */
export interface NapiConfig {
  /** Retry configuration */
  retry?: NapiRetryConfig
  /** Execution limits (concurrency, timeout per tool call) */
  limits?: NapiExecutionLimits
  /** Resource limits for the Monty sandbox */
  resourceLimits?: NapiResourceLimits
  /** Policy configuration */
  policy?: NapiPolicyConfig
}

export interface NapiExecutionLimits {
  timeoutMs?: number
  maxConcurrent?: number
}

/** Result of executing a script, returned to JS. */
export interface NapiExecutionResult {
  output: any
  stdout: string
  stderr: string
  trace: Array<NapiTraceEntry>
  stats: NapiExecutionStats
}

export interface NapiExecutionStats {
  totalDurationMs: number
  montyExecutionMs: number
  externalCalls: number
  memoryPeakBytes: number
  stepsExecuted: number
}

export interface NapiPolicyConfig {
  defaultAction?: string
  rules?: Array<NapiPolicyRule>
}

export interface NapiPolicyRule {
  matchPattern: string
  action: string
  rateLimit?: string
}

export interface NapiResourceLimits {
  maxExecutionTimeMs?: number
  maxMemoryBytes?: number
  maxStackDepth?: number
  maxExternalCalls?: number
  maxCodeLength?: number
}

export interface NapiRetryConfig {
  maxRetries?: number
  baseDelayMs?: number
}

/** Search result returned to JS. */
export interface NapiSearchResult {
  name: string
  description?: string
  inputSchema: any
  outputSchema?: any
}

/** Tool definition passed from JS when registering a tool. */
export interface NapiToolDefinition {
  name: string
  description?: string
  inputSchema: any
  outputSchema?: any
}

export interface NapiTraceEntry {
  toolName: string
  input: any
  output?: any
  error?: string
  durationMs: number
  retries: number
}
